services:
  api:
    build:
      context: api
      additional_contexts:
      - config=config
    container_name: lucos_configy
    ports:
      - $PORT:$PORT
    environment:
      - PORT
    image: lucas42/lucos_configy:${VERSION:-latest}
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:${PORT}/_info"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s
    restart: always
