
.dotfiles:
.github-test:
# lucos is primarily documentation rather than a script, but doesn't warrant its own type
lucos:
    unsupervisedAgentCode: true
lucos_agent:
    unsupervisedAgentCode: true
lucos_agent_coding_sandbox:
    unsupervisedAgentCode: true
lucos_antigravity_config:
    unsupervisedAgentCode: true
lucos_claude_config:
    unsupervisedAgentCode: true
lucos_contacts_fb_import:
lucos_contacts_gphotos_import:
# lucos_docker_health will become a system once built; script for now to avoid inapplicable conventions
lucos_docker_health:
lucos_mockauthentication:
lukeblaney_cv:
