systems:
    lucos_arachne:
        domain: arachne.l42.eu
        http_port: 8033
        hosts:
            - avalon
    lucos_authentication:
        domain: auth.l42.eu
        http_port: 8006
        hosts:
            - avalon
    lucos_backups:
        domain: backups.l42.eu
        http_port: 8027
        hosts:
            - avalon
    lucos_configy:
        domain: configy.l42.eu
        http_port: 8034
        hosts:
            - avalon
    lucos_contacts:
        domain: contacts.l42.eu
        http_port: 8013
        hosts:
            - avalon
    lucos_contacts_fb_import:
    lucos_contacts_googlesync_import:
        hosts:
            - avalon
    lucos_contacts_gphotos_import:
    lucos_creds:
        domain: creds.l42.eu
        http_port: 8031
        hosts:
            - avalon
    lucos_deploy_orb:
    lucos_dns:
        domain: dns.l42.eu
        hosts:
            - avalon
    lucos_eolas:
        domain: eolas.l42.eu
        http_port: 8032
        hosts:
            - avalon
    lucos_locations:
        domain: locations.l42.eu
        http_port: 8028
        hosts:
            - avalon
    lucos_loganne:
        domain: loganne.l42.eu
        http_port: 8019
        hosts:
            - avalon
    lucos_mail:
        domain: mail.l42.eu
        http_port: 8022
        hosts:
            - avalon
    lucos_media_import:
        hosts:
            - xwing
    lucos_media_linuxplayer:
        hosts:
            - xwing
            - salvare
    lucos_media_manager:
        domain: ceol.l42.eu
        http_port: 8001
        hosts:
            - avalon
    lucos_media_metadata_api:
        domain: media-api.l42.eu
        http_port: 3002
        hosts:
            - avalon
    lucos_media_metadata_manager:
        domain: media-metadata.l42.eu
        http_port: 8020
        hosts:
            - avalon
    lucos_media_seinn:
        domain: seinn.l42.eu
        http_port: 3001
        hosts:
            - avalon
    lucos_media_weightings:
        domain: media-weighting.l42.eu
        http_port: 8023
        hosts:
            - avalon
    lucos_monitoring:
        domain: monitoring.l42.eu
        http_port: 8015
        hosts:
            - avalon
    lucos_notes:
        domain: notes.l42.eu
        http_port: 8004
        hosts:
            - avalon
    lucos_private:
        domain: private.l42.eu
        http_port: 8016
        hosts:
            - xwing
    lucos_repos:
        domain: repos.l42.eu
        http_port: 8030
        hosts:
            - avalon
    lucos_root:
        domain: l42.eu
        http_port: 8003
        hosts:
            - avalon
    lucos_router:
        hosts:
            - avalon
            - xwing
    lucos_scenes:
        domain: scenes.l42.eu
        http_port: 8026
        hosts:
            - avalon
    lucos_schedule_tracker:
        domain: schedule-tracker.l42.eu
        http_port: 8024
        hosts:
            - avalon
    lucos_static_media:
        domain: staticmedia.l42.eu
        http_port: 8017
        hosts:
            - xwing
    lucos_time:
        domain: am.l42.eu
        http_port: 8008
        hosts:
            - avalon
    lukeblaney_co_uk:
        domain: lukeblaney.co.uk
        http_port: 8025
        hosts:
            - avalon
    pici:
        hosts:
            - xwing
            - salvare
    semweb:
        domain: semweb.lukeblaney.co.uk
        http_port: 8029
        hosts:
            - avalon
    tfluke:
        domain: app.tfluke.uk
        http_port: 3000
        hosts:
            - avalon

volumes:
    lucos_authentication_config:
        description: Configuration Data for authentication
        recreate_effort: small
    lucos_contacts_db_data:
        description: Personal data about contacts
        recreate_effort: huge
    lucos_contacts_staticfiles:
        description: Sharing static assets between docker containers
        recreate_effort: automatic
    lucos_loganne_state:
        description: Recent event logs
        recreate_effort: tolerable
    lucos_media_metadata_api_db:
        description: Data about media files
        recreate_effort: huge
    lucos_notes_stateFile:
        description: Todo list notes
        recreate_effort: considerable
    lucos_router_generatedconfig:
        description: Routing configuration
        recreate_effort: automatic
    lucos_router_letsencrypt:
        description: TLS certificates
        recreate_effort: automatic
    lucos_schedule_tracker_db:
        description: Recent results of scheduled jobs
        recreate_effort: automatic
    lucos_media_import_media:
        description: Remote volume on NAS
        recreate_effort: remote
        skip_backup: true
    lucos_private_medlib:
        description: Remote volume on NAS
        recreate_effort: remote
        skip_backup: true
    lucos_router_generatedconfig:
        description: Routing configuration
        recreate_effort: automatic
    lucos_router_letsencrypt:
        description: TLS certificates
        recreate_effort: automatic
    lucos_static_media_public:
        description: Remote volume on NAS
        recreate_effort: remote
        skip_backup: true
    pici_docker:
        description: Cache of docker layers etc used when building new images
        recreate_effort: automatic
        skip_backup: true
    lucos_creds_store:
        description: Credentials used by lucos services.  Both between services within lucos and to third party services.
        recreate_effort: considerable
    lucos_media_manager_stateFile:
        description: The current state of media player, including playlist, volume, is-playing and connected devices.
        recreate_effort: tolerable
    lucos_locations_store:
        description: Historic location data
        recreate_effort: huge
    lucos_locations_config:
        description: Configuration for OwnTracks Recorder
        recreate_effort: automatic
    lucos_locations_mosquitto_data:
        description: Message queue data
        recreate_effort: automatic
    lucos_locations_mosquitto_log:
        description: Message queue logs
        recreate_effort: automatic
    lucos_eolas_db_data:
        description: Personally curated Knowledge Graph
        recreate_effort: considerable
    lucos_eolas_staticfiles:
        description: Sharing static assets between docker containers
        recreate_effort: automatic
    lucos_arachne_fuseki_data:
        description: Data from the arachne triple store, gathered from other lucOS systems
        recreate_effort: automatic
        skip_backup: true
    lucos_arachne_typesense_data:
        description: Data from the arachne search index, gathered from other lucOS systems
        recreate_effort: automatic
        skip_backup: true
    lucos_media_metadata_api_exports:
        description: Automated exports of media metadata
        recreate_effort: automatic
    

hosts:
    avalon:
        domain: avalon.s.l42.eu
    xwing:
        domain: xwing.s.l42.eu
    salvare:
        domain: salvare.s.l42.eu

components:
    lucos_navbar:
    lucos_search_component:
    lucos_time_component:
    restful-queue: